### ISSUE TITLE
Setup wordpress with mysql using docker.

### ISSUE THREAD

**Issue by jithinsajeev** [jithinsajeev/NagiosXI#2]
Setup wordpress with mysql using docker.

**Comment by jithinsajeev** [comment]
docker-compose.yml
```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: db1
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpass

   web:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       DB_HOST: db:3306
       DB_USER: dbuser
       DB_PASSWORD: dbuserpass
volumes:
    db_data: {}
```
